# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  nerdstoresalesapi:
    image: nerdstoresalesapi
    build:
      context: .
      dockerfile: src/NerdStore.Sales.Api/Dockerfile
    ports:
      - 80
