name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        registry: ${{ secrets.DOCKER_CONTAINER_REGISTRY }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
      
    - name: Build the Docker image
      run: |
        docker build . -t docker-whal ./Dockerfile.txt --tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/nerdstorecontainer:latest
        docker tag ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/nerdstorecontainer:latest ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/nerdstorecontainer:$(date +%s)
        docker push ${{ secrets.DOCKER_CONTAINER_REGISTRY }}/nerdstorecontainer
